name: local_heroes
description: A Flutter app showcasing local changemakers and unsung heroes in the community.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_card_swiper: ^7.0.0
  provider: ^6.0.0
  share_plus: ^7.0.0
  path_provider: ^2.0.0
  csv: ^5.0.0
  confetti: ^0.7.0
  cached_network_image: ^3.3.0
  url_launcher: ^6.0.0
  cupertino_icons: ^1.0.2
  http: ^1.1.0
  audioplayers: ^6.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.jpg"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/images/logo.jpg"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/sound/
